print("Welcome! Get birthday wishes for friends , family and close ones!")
wish_1 = input("Please enter the first birthdate: ")
print("Wishing you a Happy Birthday on",wish_1,"!")
wish_2 = input("Please enter the second birthdate: ")
print("Wishing you a Happy Birthday on",wish_2,"!")
wish_3 = input("Please enter the third birthdate: ")
print("Wishing you a Happy Birthday on",wish_3,"!")
wish_4 = input("Please enter the fourth birthdate: ")
print("Wishing you a Happy Birthday on",wish_4,"!")
wish_5 = input("Please enter the fifth birthdate: ")
print("Wishing you a Happy Birthday on",wish_5,"!")
print("Thank you!")
